name: On PR, Build, Publish to Azure Bucket

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
env:
  SITE_DIR: ${{ github.ref }}
  #SITE_DIR: subsite
on:
  workflow_dispatch:
  # We have another workflow for pushing directly to dev
  push:
    branches:
      - 'dev'
    tags:
    - test-*
  pull_request:
    types: [opened, reopened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-html:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Get branch name
      id: getbr
      uses: tj-actions/branch-names@v6
    
    - name: Get the branch output
      run: echo "The output of get-branch is ${{ steps.getbr.outputs.ref_branch }}"
      
    - name: Remove last part of PR ref
      uses: mad9000/actions-find-and-replace-string@3
      id: findandreplace
      with:
        source: ${{ steps.getbr.outputs.ref_branch }}
        find: '/merge'    
        replace: '' 
        
    - name: Get the above output
      run: echo "The output of findandreplace is ${{ steps.findandreplace.outputs.value }}"

    - name: Checkout Dev
      uses: actions/checkout@v3
    
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - run: python -m pip install --upgrade pip setuptools wheel
    
    # Needed when using more than one repo
    # add 'monorepo' to mkdocs.yml file under plugins
    - run: pip install mkdocs-monorepo-plugin

    # add lightbox
    # zoom images
    - name: Install MkDocs Light Box
      run: pip install mkdocs-glightbox

    # add multirepo to support pulling docs from other repos
    - name: Install multirepo
      run: pip install mkdocs-multirepo-plugin
    
    # Commenting out material insiders install until get proper token back.
    - run: pip install git+https://${{ env.GH_TOKEN }}@github.com/squidfunk/mkdocs-material-insiders.git
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    - run: pip install mkdocs
    #- run: pip install mkdocs-material
    
    - name: Build MkDocs Site
      run: mkdocs build --no-directory-urls
      env:
        AccessToken: ${{ secrets.QUIX_STREAMS_ACCESS_TOKEN }}
        
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 
          
    - name: Create container in Azure blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az login --service-principal -u 172103f9-7886-4f00-a49e-621461d234e1 -p ${{ secrets.DOCSBOT_SECRET }} --tenant 07dc27cd-da6f-4de6-b83d-c4eed0a10602
            az storage container create --name pr${{ steps.findandreplace.outputs.value }} --public-access container --account-name quixdocsdev --auth-mode key

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az login --service-principal -u 172103f9-7886-4f00-a49e-621461d234e1 -p ${{ secrets.DOCSBOT_SECRET }} --tenant 07dc27cd-da6f-4de6-b83d-c4eed0a10602
            az storage blob upload-batch --overwrite true --account-name quixdocsdev --auth-mode key -d 'pr${{ steps.findandreplace.outputs.value }}' -s site

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
          
    - name: Echo Site URL
      run: echo "Docs preview site available at https://quixdocsdev.blob.core.windows.net/pr${{ steps.findandreplace.outputs.value }}/index.html"
      
    - name: Comment Site URL    
      uses: mshick/add-pr-comment@v2
      with:
        if: always()
        message: |
          Docs preview site available at https://quixdocsdev.blob.core.windows.net/pr${{ steps.findandreplace.outputs.value }}/index.html
        message-failure: |
            Build failed. URL was not updated.
    
#     - name: Slack Notification
#       uses: rtCamp/action-slack-notify@v2
#       env:
#         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#         SLACK_CHANNEL: devrel
#         SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
#         SLACK_ICON: https://github.com/rtCamp.png?size=48
#         SLACK_MESSAGE: ':rocket: A build just left the launch pad\nPreview site available at https://quixdocsdev.blob.core.windows.net/pr${{ steps.findandreplace.outputs.value }}/index.html'
#         SLACK_TITLE: Docs Build & Deploy
#         SLACK_USERNAME: GitHubBuildBot
      
    - name: Send Slack notification
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        # For posting a rich message using Block Kit
        payload: |
          {
            "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":rocket: A build just left the launch pad\nPreview site available at https://quixdocsdev.blob.core.windows.net/pr${{ steps.findandreplace.outputs.value }}/index.html"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
